add_newline = true

format = """
$character\
$directory\
$git_branch \
[✗](bold #a8a947) 
"""

[character]
disabled = false
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_visual_symbol = '[](bold white)'


[git_branch]
format='[git:\(](bold #6348ec)[$branch](bold red)[\)](bold #6348ec)'

